# source webapp/.env
# docker build --build-arg REACT_APP_BACKEND_URI=$REACT_APP_BACKEND_URI -f docker/webapp/Dockerfile.nginx -t chat-copilot-webapp-nginx .

# builder
FROM node:lts-alpine as builder

ARG REACT_APP_BACKEND_URI
ENV REACT_APP_BACKEND_URI $REACT_APP_BACKEND_URI

WORKDIR /app
COPY webapp/ .
RUN yarn install \
  --prefer-offline \
  --frozen-lockfile \
  --non-interactive \
  --production=false

RUN yarn build

# final stage/image
FROM nginx:stable-alpine
EXPOSE 3000
RUN sed -i 's/80/3000/g' /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
